### ISSUE TITLE
The whole app is a tad to wide (on iOS under Chrome)

### ISSUE THREAD

**Issue by pfinette** [mozilla/firehug#69] opened 2013-09-30 17:39 UTC
See screenshot from the Thank You screen for the 3 Questions as an example. Note that this is everywhere - the app is a few pixel to wide to not scroll horizontally.

![thank you screen](https://f.cloud.github.com/assets/307225/1239207/320567a6-29f7-11e3-82a4-c7b40aa4fb51.png)

**Comment by pfinette** [comment] 2013-09-30 17:46
Confirming: This seems to be a Chrome/iOS issue. Looks fine on Safari/iOS 7.

**Comment by pfinette** [comment] 2013-09-30 17:51
AND... the Thank You screen is still too wide even on Safari/iOS. ;)

Interestingly - once you come back from the Thank You screen the whole app is too wide. Is there CSS bleeding?

**Comment by digitarald** [comment] 2013-09-30 18:06
Saw this before. I assume this is only Thankyou screen.

**Comment by pfinette** [comment] 2013-09-30 18:07
It seems to bleed Harald. Once you hit it it shows everywhere. Which is kinda weird.

**Comment by digitarald** [comment] 2013-10-01 00:03
@pfinette can you re-test? I couldn't reproduce, so I might have fixed it in 32402c025efdab6afe8ee4536435dba3d4fceb21.

**Comment by digitarald** [comment] 2013-10-01 21:58
Closing for now, re-open if persists.

**Closed as completed by digitarald** 2013-10-01 21:58 UTC
Labels: bug, interface
