### ISSUE TITLE
Schedule thinks I go to Toronto (I am going to Santa Clara)

### ISSUE THREAD

**Issue by pfinette** [mozilla/firehug#67] opened 2013-09-30 17:30 UTC
On the mobile view I get dropped into the Toronto view, on the desktop experience I see only the dropdown without a preselected location.

![empty schedule on desktop](https://f.cloud.github.com/assets/307225/1239129/ffdaca38-29f5-11e3-90d5-f31a895062a7.png)

**Comment by digitarald** [comment] 2013-09-30 18:10
Duplicate of #64

**Closed as completed by digitarald** 2013-09-30 18:10 UTC
